name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"     # executa a cada 12h
  workflow_dispatch:            # permite rodar manualmente
  push:
    branches:
      - main                   # executa quando fizer push na branch main

jobs:
  generate:
    permissions:
      contents: write           # necessário para criar a branch 'output'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
